name: Release Binaries

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  workflow_dispatch:


jobs:
  releases-matrix:
    permissions: write-all
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude: []
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run Tests
        run: go test -v ./...

      - name: Git Semantic Version
        id: semantic_version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"

      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.PAT }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23
          ldflags: "-s -w -extldflags -static"
          release_tag: "${{ steps.semantic_version.outputs.version }}"
          release_name: "${{ steps.semantic_version.outputs.version }}"
          pre_command: export CGO_ENABLED=0
          binary_name: "ezdrop"
          asset_name: "ezdrop-${{ matrix.goos }}-${{ matrix.goarch }}"

