name: Release Binaries

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  workflow_dispatch:


jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.semantic_version.outputs.version_tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Git Semantic Version
        id: semantic_version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"

      - name: Create Tag Release
        uses: beyond5959/create-release-github@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ steps.semantic_version.outputs.version_tag }}
          release_name: ${{ steps.semantic_version.outputs.version_tag }}          
  
  releases-matrix:
    needs: create-release-tag
    permissions: write-all
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude: []
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.PAT }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23
          ldflags: "-s -w -extldflags -static"
          release_tag: "${{ needs.create-release-tag.outputs.version_tag }}"
          release_name: "${{ needs.create-release-tag.outputs.version_tag }}"
          pre_command: export CGO_ENABLED=0
          binary_name: "ezdrop"
          asset_name: "ezdrop-${BINARY_NAME}-${RELEASE_TAG}-${GOOS}-${GOARCH}"
          md5sum: false
