name: Release Binaries

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  workflow_dispatch:


jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude: []
    steps:
    - uses: actions/checkout@v2

    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v6.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'v'
        tag_template: 'yyyy-mm-dd-i'

    - uses: wangyoucao577/go-release-action@v1.16
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.23
        build_flags: -v
        ldflags: "-w -s"
        release_tag: ${{ steps.generate_release_tag.outputs.tag }}
